Create table DEPARTMENT(

Depart_Name VARCHAR(11) NOT NULL,

Depart_ID CHAR(3) PRIMARY KEY

);

--------------------------------------------

Create table MANAGER(

MANGAER_PHONE INT NOT NULL,

MANAGER_EMAIL VARCHAR(28) NOT NULL,

MANAGER_LNAME VARCHAR(8) NOT NULL,

MANAGER_FNAME VARCHAR(6) NOT NULL,

MANAGER_ID INT PRIMARY KEY,

DEPART_ID CHAR(3) NOT NULL REFERENCES DEPARTMENT

);
---------------------------------------------------
CREATE TABLE EMPLOYEE (

EMPLOY_PHONE INT NOT NULL,

EMPLOY_LNAME VARCHAR(8) NOT NULL,

EMPLOY_FNAME VARCHAR(10) NOT NULL,

EMPLOY_EMAIL VARCHAR(28) NOT NULL,

EMPLOY_ID CHAR(5) PRIMARY KEY,

DEPART_ID CHAR(3) NOT NULL REFERENCES DEPARTMENT

);
----------------------------------------------------------
CREATE TABLE EXPENSE_REPORT( 

EXPENSEREPORT_NUM INT PRIMARY KEY,

EXPENSEREPORT_DATE DATE NOT NULL,

EXPENSE_TOTAL FLOAT(5) DEFAULT 0.00 NOT NULL,

EXPENSEREPORT_STATUS VARCHAR(10) NOT NULL,

EMPLOY_ID CHAR(5) NOT NULL REFERENCES EMPLOYEE,

);
-------------------------------------------------------------------
CREATE TABLE EXPENSE_ITEM (

EXPENSEITEM_ID CHAR(6) PRIMARY KEY,

EXPENSEITEM_DESCRIPT VARCHAR(30) NOT NULL,

EXPENSEITEM_NAME VARCHAR(30) NOT NULL,

EXPENSEREPORT_NUM INT NOT NULL REFERENCES EXPENSE_REPORT 

);
------------------------------------------------------------------
CREATE TABLE EXPENSE_TIME ( 
EMPLOY_ID	CHAR(5)	NOT NULL,

EXPENSEITEM_ID	CHAR(6) NOT NULL,

EXPENSEREPORT_NUM	INT NOT NULL,

EXPENSE_AMOUNT	FLOAT(5) DEFAULT 0.00 NOT NULL,

INITIAL_TIME CHAR(20) NOT NULL,

PRIMARY KEY (EMPLOY_ID, EXPENSEITEM_ID, EXPENSEREPORT_NUM),

FOREIGN KEY (EMPLOY_ID) REFERENCES EMPLOYEE,

FOREIGN KEY (EXPENSEITEM_ID) REFERENCES EXPENSE_ITEM,

FOREIGN KEY (EXPENSEREPORT_NUM) REFERENCES EXPENSE_REPORT

);
